apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rl-by-header
config:
  second: 10001
  limit_by: header
  policy: local
  header_name: X-Credential-Identifier
plugin: rate-limiting
